import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generatePOPDF = (po) => {
    const doc = new jsPDF();

    // --- Header ---
    doc.setFontSize(22);
    doc.setTextColor(184, 134, 11); // Gold/Bronze color (#B8860B)
    doc.text('KG INFRA - PURCHASE ORDER', 105, 20, { align: 'center' });

    // --- Status Badge ---
    const status = po.deliveryStatus || 'PENDING';
    doc.setFontSize(10);
    doc.setFillColor(
        status === 'DELIVERED' ? 220 : status === 'IN_TRANSIT' ? 220 : 255, 
        status === 'DELIVERED' ? 252 : status === 'IN_TRANSIT' ? 240 : 248, 
        status === 'DELIVERED' ? 231 : status === 'IN_TRANSIT' ? 255 : 232
    );
    doc.setDrawColor(status === 'DELIVERED' ? 16 : status === 'IN_TRANSIT' ? 37 : 194);
    // Rough estimation for badge background
    doc.rect(160, 25, 35, 8, 'F');
    doc.setTextColor(status === 'DELIVERED' ? 21 : status === 'IN_TRANSIT' ? 30 : 154, status === 'DELIVERED' ? 128 : status === 'IN_TRANSIT' ? 64 : 52, status === 'DELIVERED' ? 61 : status === 'IN_TRANSIT' ? 175 : 18);
    doc.text(status, 177.5, 30.5, { align: 'center' });

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text(`PO Number: ${po.poNumber}`, 14, 40);
    doc.setFont(undefined, 'normal');
    doc.text(`Date: ${new Date(po.date).toLocaleDateString()}`, 14, 47);

    // --- Party Details & Warehouse ---
    doc.setFont(undefined, 'bold');
    doc.text('Party Details:', 14, 60);
    doc.setFont(undefined, 'normal');
    doc.text(`Name: ${po.party.name}`, 14, 67);
    doc.text(`Phone: ${po.party.phone || 'N/A'}`, 14, 74);
    doc.text(`Address: ${po.party.address || 'N/A'}`, 14, 81);
    doc.text(`Email: ${po.party.email || 'N/A'}`, 14, 88);

    doc.setFont(undefined, 'bold');
    doc.text('Delivery Location:', 120, 60);
    doc.setFont(undefined, 'normal');
    doc.text(`Warehouse: ${po.warehouse?.name || 'N/A'}`, 120, 67);
    doc.text(`Location: ${po.warehouse?.location || 'N/A'}`, 120, 74);

    // --- Items Table ---
    const tableData = po.items.map((item, index) => [
        index + 1,
        item.productName || item.product?.name || 'N/A',
        item.quantity,
        item.unitPrice ? `INR ${item.unitPrice}` : '—',
        item.amount ? `INR ${item.amount}` : '—'
    ]);

    autoTable(doc, {
        startY: 95,
        head: [['#', 'Item Name', 'Quantity', 'Unit Price', 'Amount']],
        body: tableData,
        theme: 'striped',
        headStyles: { fillColor: [184, 134, 11], textColor: 255, fontStyle: 'bold' },
        styles: { fontSize: 10, cellPadding: 3 },
        columnStyles: {
            0: { cellWidth: 10 },
            2: { halign: 'center' },
            3: { halign: 'right' },
            4: { halign: 'right' }
        },
        margin: { top: 10 }
    });

    // --- Totals ---
    const finalY = (doc.lastAutoTable ? doc.lastAutoTable.finalY : 95) + 10;
    doc.setFont(undefined, 'bold');
    doc.text(`Total Quantity: ${po.totals.totalQuantity}`, 140, finalY);
    if (po.totals.totalAmount > 0) {
        doc.text(`Total Amount: INR ${po.totals.totalAmount}`, 140, finalY + 7);
    }

    // --- Footer ---
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text('This is a computer generated document.', 105, 285, { align: 'center' });
        doc.setFont(undefined, 'bold');
        doc.setTextColor(0);
        doc.text('Generated by Kriyona Infotech', 105, 292, { align: 'center' });
    }

    doc.save(`${po.poNumber}.pdf`);
};
